# Generated by Django 3.1.2 on 2020-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('task', models.TextField(verbose_name='Description')),
                ('author', models.CharField(default='', max_length=20, verbose_name='Author')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is_done')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'My tasks',
            },
        ),
    ]
