# Generated by Django 3.1.2 on 2020-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201101_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
    ]
