# Generated by Django 3.1.2 on 2020-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201101_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Author'),
        ),
    ]
